### ISSUE TITLE
could you help me notification

### ISSUE THREAD

**Issue by maxicabanillas78** [firebase/codelab-friendlychat-android#101]
could you help me how can I do so when a new message arrives from someone send me a notification when I'm not active

**Comment by morganchen12** [comment]
Hey @maxicabanillas78, this question is better suited for a platform like StackOverflow.

To learn how to send a notification to an Android app, take a look at our [FCM getting started on Android guide](https://firebase.google.com/docs/cloud-messaging/android/client).
