### ISSUE TITLE
Cannot resolve method 'getDownloadUrl' in 'TaskSnapshot'

### ISSUE THREAD

**Issue by mjmaurya** [firebase/codelab-friendlychat-android#113]
Cannot resolve method 'getDownloadUrl' in 'TaskSnapshot'

![geturl](https://user-images.githubusercontent.com/45433443/88471610-ea9caf80-cf28-11ea-8fca-1257ec30d1c9.PNG)

**Comment by samtstern** [comment]
@mjmaurya that seems to be working as intended.  Your code does not seem to match the codelab:
https://codelabs.developers.google.com/codelabs/firebase-android/#8

`UploadTask.TaskSnapshot` does not have a `getDownloadUrl()` method:
https://firebase.google.com/docs/reference/android/com/google/firebase/storage/UploadTask.TaskSnapshot
