### ISSUE TITLE
mUsername not present

### ISSUE THREAD

**Issue by jgedri** [firebase/codelab-friendlychat-android#150]
I've looked through the onCreate method in MainActivity, but there isn't a variable named mUsername.

**Comment by samtstern** [comment]
@jgedri I recently removed that, can you show me which part of the instructions still mentions it?

**Comment by jgedri** [comment]
I'm pretty sure it's at the beginning of Step 5.

**Comment by samtstern** [comment]
@jgedri thanks!  I see it now and I will get it fixed.

**Comment by samtstern** [comment]
I am changing that sentence to:

> Now let's modify `MainActivity.java` to send the user to the sign-in screen whenever they open the app and are unauthenticated.  Add the following to the `onCreate` method just after `setContentView()` is called:

**Comment by jgedri** [comment]
> 
> 
> @jgedri thanks! I see it now and I will get it fixed.

You're welcome. :-)
