### ISSUE TITLE
Language difference in Codelabs instructions and source files provided

### ISSUE THREAD

**Issue by absophola** [firebase/codelab-friendlychat-android#168]
The Codelabs instructions are all in Java but the files provided for `build-android-start` are in Kotlin. Is there something I am missing in the instructions? Is there a Java version of the files for the linked Codelabs?

**Comment by kastrahl** [comment]
the labs provide mainactivity.java code but we're given .kt files

**Comment by andresinho20049** [comment]
Looking in other branches I found the code in Java, but if a migration was made to Kotlin, because they did not create another project in kotlin equal to the codelab material-components-android-codelabs

**Comment by kastrahl** [comment]
i've found the branch names ss-androidx migration to be perfectly working with the code and dependencies   with the issue of GoogleApiClient being depreciated . im searching for workaround

**Comment by samtstern** [comment]
Hey everyone sorry about this, it's my fault. I'll get it fixed today so that everything is Kotlin.

**Comment by samtstern** [comment]
The codelab is now published to use Kotlin:
https://firebase.google.com/codelabs/firebase-android
