### ISSUE TITLE
I separated the Java and Kotlin version

### ISSUE THREAD

**Issue by andresinho20049** [firebase/codelab-friendlychat-android#169]
## Equal version of codelabs

I created a _new branch_ separating the _java and kotlin version_ of the codelab, but since I am not allowed to go up in that repository, I went up the code in my repository for a possible pull request of the changes.

https://github.com/andresinho20049/AndroidCodelab-BuildFriendlyChat/tree/first-codelab-java-kotlin

**Comment by kastrahl** [comment]
https://github.com/firebase/codelab-friendlychat-android/pull/162/files 
this is where error arose

**Comment by samtstern** [comment]
See #168
