### ISSUE TITLE
messageImageView typo in step 7

### ISSUE THREAD

**Issue by djnotes** [firebase/codelab-friendlychat-android#194]
Apparently, `binding.messageImageView` inside the ImageViewHolder class should be changed to `binding.messengerImageView`.

**Comment by thatfiredev** [comment]
@djnotes Do you mind showing me a link to the file or codelab step where you think this change is necessary?

**Comment by djnotes** [comment]
https://firebase.google.com/codelabs/firebase-android#6 under FriendlyMessageAdapter.kt

**Comment by djnotes** [comment]
Thanks Rosario for checking. Message ID: ***@***.***>

I think you're right.

 For some reason in this part of the code lab, my binding was unable to resolve binging.messageImageView and I thought it might be a typo.

**Comment by thatfiredev** [comment]
@djnotes glad you figured it out. :)

I'l close this now.
