### ISSUE TITLE
android-starter - Add Messages to the On-device Index - Google App updates

### ISSUE THREAD

**Issue by kenthua** [firebase/codelab-friendlychat-android#33]
1. Start up the FriendlyChat app and send a new message with the text Hi world!
2. Go to the Google app, switch to In Apps and search for Hi world.

In more recent versions for the Google app, it is no longer "In Apps" it is under the "Personal" category.

3. Confirm that the message can be found in the Google app.
4. Tap on the result and confirm the FriendlyChat app opens.

**Comment by samtstern** [comment]
Closing this old issue since Google Search app no longer supports personal content indexing.
