### ISSUE TITLE
is:issue is:oError: Program type already present: com.google.android.gms.internal.measurement.zzdzpen 

### ISSUE THREAD

**Issue by Ebadullahamini** [firebase/codelab-friendlychat-android#62]

**Comment by adilmirza21** [comment]
I am facing the below :
Program type already present: com.google.android.gms.internal.measurement.zzc


Please help

**Comment by samtstern** [comment]
Apologies for never getting to this old issue but I believe it is no longer relevant so going to close it.  Our CI shows that the build is passing.
