### ISSUE TITLE
Step 5: "File > Sync Project with Gradle Files" "Error: No such property: GradleVersion for class jetGradlePlugin"

### ISSUE THREAD

**Issue by siliconmoo** [firebase/codelab-friendlychat-android#79]
Step 5: "File > Sync Project with Gradle Files" "Error: No such property: GradleVersion for class jetGradlePlugin"

Using Android Studio for Linux, version 3.0.1 (downloaded 6/2019)

gradle-wrapper.properties (downloaded 6/19/2019)
#Tue Feb 21 11:31:35 EST 2017
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-5.4-all.zip

**Comment by samtstern** [comment]
@siliconmoo sorry for never responding here.  Since this issue references some old tooling which is no longer in use in this repo I am going to close it.  Our CI shows that the repo builds successfully on the current versions.
