### ISSUE TITLE
Can not build: io.fabric not found

### ISSUE THREAD

**Issue by GunnarBernsteinHH** [firebase/codelab-friendlychat-android#92]
Build file 'C:\Development\Android\Test\friendlychat-android\build-android\app\build.gradle' line: 2

* What went wrong:
A problem occurred evaluating project ':build-android:app'.
> Plugin with id 'io.fabric' not found.

This may have to do with newest Android Studio 3.6.
I get so many errors, I can not resolve:
A problem occurred configuring project ':build-android:app'.
> compileSdkVersion is not specified.

Changed gradle to 5.6.4 because 5.4.1 had an unsupported issue.
Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.

During my attempts to update the packages I also got a number of AndroidX warnings. 
Personally I think, this project should be updated to use AndroidX.

**Comment by samtstern** [comment]
@GunnarBernsteinHH I just went through and updated a lot of things today, can you try a fresh clone of the code and see if that works?

**Comment by samtstern** [comment]
(one of the things I did today was update to AndroidX as well)

**Comment by GunnarBernsteinHH** [comment]
Hi Sam,

thanks for putting so much work into it.

Unfortunately, the errors are identical. I see, you have updated gradle 
and AndroidX, as well as the dependencies and compile versions.

I of course invalidated and rebuild, but no success.

Find the log below.

When I comment out apply fabric.io in all three places, it compiles and 
runs fine. I only get a warning:

 > Task :build-android:app:compileDebugJavaWithJavac
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

I have trouble understanding the "compileSdkVersion is not specified", 
which is clearly inside.

I did this with two windows machines and a Manjaro installation. I tried 
Manjaro, because I had not updated to AS 3.6 yet, but the gradle 
complained about that. All resulted in the same error situation.

The gradle log file contains too much personal information, so here are 
just the errors:

09:44:31.426 [INFO] 
[org.gradle.launcher.daemon.server.DefaultIncomingConnectionHandler] 
Received command: Build{id=1b958c67-f405-4848-9131-9acad98cd7a9, 
currentDir=C:\Development\Android\Test\friendlychat-android}.
09:44:31.426 [DEBUG] 
[org.gradle.launcher.daemon.server.DefaultIncomingConnectionHandler] 
Starting executing command: 
Build{id=1b958c67-f405-4848-9131-9acad98cd7a9, 
currentDir=C:\Development\Android\Test\friendlychat-android} with 
connection: socket connection from /127.0.0.1:58926 to /127.0.0.1:58927.
09:44:31.428 [ERROR] 
[org.gradle.launcher.daemon.server.DaemonStateCoordinator] Command 
execution: started DaemonCommandExecution[command = 
Build{id=1b958c67-f405-4848-9131-9acad98cd7a9, 
currentDir=C:\Development\Android\Test\friendlychat-android}, connection 
= DefaultDaemonConnection: socket connection from /127.0.0.1:58926 to 
/127.0.0.1:58927] after 0.0 minutes of idle

Best Gunter

----------------

Executing tasks: [:grow-android-start:app:assembleDebug, 
:build-android-start:app:assembleDebug, 
:build-android:app:assembleDebug] in project 
C:\Development\Android\Test\friendlychat-android

The client will now receive all logging from the daemon (pid: 4460). The 
daemon log file: C:\Users\gsc\.gradle\daemon\5.6.4\daemon-4460.out.log
Starting 3rd build in daemon [uptime: 52.319 secs, performance: 96%]
Closing daemon's stdin at end of input.
The daemon will no longer process any standard input.
Using 8 worker leases.
Starting Build
Settings evaluated using settings file 
'C:\Development\Android\Test\friendlychat-android\settings.gradle'.
Using local directory build cache for the root build (location = 
C:\Users\gsc\.gradle\caches\build-cache-1, removeUnusedEntriesAfter = 7 
days).
Configuration on demand is an incubating feature.
Projects loaded. Root project using build file 
'C:\Development\Android\Test\friendlychat-android\build.gradle'.
Included projects: [root project 'friendlychat-android', project 
':build-android', project ':build-android-start', project 
':grow-android-start', project ':build-android:app', project 
':build-android-start:app', project ':grow-android-start:app']

 > Configure project :
Evaluating root project 'friendlychat-android' using build file 
'C:\Development\Android\Test\friendlychat-android\build.gradle'.

 > Configure project :grow-android-start:app
Evaluating project ':grow-android-start:app' using build file 
'C:\Development\Android\Test\friendlychat-android\grow-android-start\app\build.gradle'.
Creating configuration androidTestUtil
Creating configuration compile
Creating configuration apk
Creating configuration provided
Creating configuration api
Creating configuration implementation
Creating configuration runtimeOnly
Creating configuration compileOnly
Creating configuration wearApp
Creating configuration annotationProcessor
Creating configuration androidTestCompile
Creating configuration androidTestApk
Creating configuration androidTestProvided
Creating configuration androidTestApi
Creating configuration androidTestImplementation
Creating configuration androidTestRuntimeOnly
Creating configuration androidTestCompileOnly
Creating configuration androidTestWearApp
Creating configuration androidTestAnnotationProcessor
Creating configuration testCompile
Creating configuration testApk
Creating configuration testProvided
Creating configuration testApi
Creating configuration testImplementation
Creating configuration testRuntimeOnly
Creating configuration testCompileOnly
Creating configuration testWearApp
Creating configuration testAnnotationProcessor
Creating configuration debugCompile
Creating configuration debugApk
Creating configuration debugProvided
Creating configuration debugApi
Creating configuration debugImplementation
Creating configuration debugRuntimeOnly
Creating configuration debugCompileOnly
Creating configuration debugWearApp
Creating configuration debugAnnotationProcessor
Creating configuration androidTestDebugCompile
Creating configuration androidTestDebugApk
Creating configuration androidTestDebugProvided
Creating configuration androidTestDebugApi
Creating configuration androidTestDebugImplementation
Creating configuration androidTestDebugRuntimeOnly
Creating configuration androidTestDebugCompileOnly
Creating configuration androidTestDebugWearApp
Creating configuration androidTestDebugAnnotationProcessor
Creating configuration testDebugCompile
Creating configuration testDebugApk
Creating configuration testDebugProvided
Creating configuration testDebugApi
Creating configuration testDebugImplementation
Creating configuration testDebugRuntimeOnly
Creating configuration testDebugCompileOnly
Creating configuration testDebugWearApp
Creating configuration testDebugAnnotationProcessor
Creating configuration releaseCompile
Creating configuration releaseApk
Creating configuration releaseProvided
Creating configuration releaseApi
Creating configuration releaseImplementation
Creating configuration releaseRuntimeOnly
Creating configuration releaseCompileOnly
Creating configuration releaseWearApp
Creating configuration releaseAnnotationProcessor
Creating configuration testReleaseCompile
Creating configuration testReleaseApk
Creating configuration testReleaseProvided
Creating configuration testReleaseApi
Creating configuration testReleaseImplementation
Creating configuration testReleaseRuntimeOnly
Creating configuration testReleaseCompileOnly
Creating configuration testReleaseWearApp
Creating configuration testReleaseAnnotationProcessor

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file 
'C:\Development\Android\Test\friendlychat-android\grow-android-start\app\build.gradle' 
line: 2

* What went wrong:
A problem occurred evaluating project ':grow-android-start:app'.
 > Plugin with id 'io.fabric' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug 
option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':grow-android-start:app'.
 > compileSdkVersion is not specified. Please add it to build.gradle

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug 
option to get more log output. Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 137ms

**Comment by samtstern** [comment]
@GunnarBernsteinHH thank you for all your efforts!  That's really strange because our CI build is passing (before we didn't have a CI build) so it must be some difference between our environment and yours ... honestly I am not sure what's going wrong.

**Comment by GunnarBernsteinHH** [comment]
Hi Sam,

I find it unlikely, that it does not work on 3 different machines.

However, looking at the documentation for fabric: "Fabric is deprecated 
and will be available until March 31, 2020 for existing users.", I 
changed it to:

applyplugin:'com.google.firebase.crashlytics'
implementation 'com.google.firebase:firebase-crashlytics:17.0.0-beta01'
classpath 'com.google.firebase:firebase-crashlytics-gradle:2.0.0-beta02'

This allowed me to compile successfully. Maybe it has to do with me not 
beeing an existing fabric user?

Since fabric.io is deprecated, I think it would be better to use the 
firebase crashlytics anyhow.

Best
Gunter


Am 27.02.2020 um 00:39 schrieb Sam Stern:

**Comment by samtstern** [comment]
@GunnarBernsteinHH I totally agree with you!  There's a real problem somewhere, I just can't reproduce it like you can so I am having trouble solving it.

The long-term solution is definitely to move to the new `firebase-crashlytics` SDK as you mentioned, however I was hoping to wait until they exit Beta before adding them to this codelab.
